3 step 1 first game
buildo/caprio-be-training pull request #4
Opened 2020-11-16 18:41 UTC by Viktor-K

**Test PLAN**
Init application with game logic.
User can input “0”, “1”, “2” and play a game of Rock (0) Paper (1) Scissors (2).
If the input command is different from the previous, an error message occurs.
The terminal shows the match-winner and commands provided for each player.

2020-11-17 14:09 UTC, gabro requested changes
Overall buona soluzione! Ho lasciato qualche suggerimento di cose da migliorare :)

2020-11-17 14:09 UTC, gabro commented on src/main/scala/command/Command.scala
> +}
Super minor, ma di solito la struttura che si segue è:

```
sealed trait Command
object Command {
  case object Exit extends Command
  case object PlayAgain extends Command
}
```

in questo modo l'oggetto `Command` fa da "namespace".

In generale non ti suggerisco di fare gerarchie nestate di "enumerations" perché poi ti si complica la vita. Suggerirei una cosa tipo

```scala
sealed trait Command
object Command {
  case object Exit extends Command
  case object PlayAgain extends Command
}

sealed trait Move
object Move {
  case object Rock extends Move
  //..
}
```

```

2020-11-17 14:09 UTC, gabro commented on src/main/scala/error/Error.scala
> +object InvaliInput extends Error("Invalid Input");
```suggestion
object InvalidInput extends Error("Invalid Input")
```

occhio ai punti e virgola che non servono ;)

2020-11-17 14:09 UTC, gabro commented on src/main/scala/error/Error.scala
> +sealed abstract case class Error(errorMessage: String) {
ok, mi spieghi i modificatori?

`sealed abstract case` non li ho mai visti tutti insieme ;)

2020-11-17 14:09 UTC, gabro commented on src/main/scala/game/Game.scala
> +    val userInput: String = scala.io.StdIn.readLine()
l'annotazione di tipo è un po' ridondante, ma è un dettaglio

2020-11-17 14:09 UTC, gabro commented on src/main/scala/game/Game.scala
> +      )
ok, qui stai facendo un check (a runtime, anche se magari non è ovvio) del sottotipo di `Command` per beccare i `PlayCommand`.

Questo è un po' il motivo per cui ti suggerivo di non fare enumerations multi-livello, che ti costringe poi ad usare questo stile non bellissimo per capire quale sottotipo hai in mano.

Senza suggerire troppo ti chiederei di studiare una soluzione alternativa :-)

Nota che 

```scala
a match {
  case foo: PlayCommand => //
}
```

è un check a runtime perché di fatto è come se stessi facendo:

```scala
if (a.isInstanceOf[PlayCommand]) {
}
```

2020-11-17 15:36 UTC, Viktor-K commented on src/main/scala/error/Error.scala
> +sealed abstract case class Error(errorMessage: String) {
Ho utilizzato il seguente criterio : 

- **sealed** - per forzare la definizioni dei sottotipi nello stesso file
- **case** - per poter utilizzare il pattern matching su questo tipo di oggetti
- **abstract class** - lo scopo era avere una classe con un metodo di default per mostrare l'errore, in modo che potesse essere utilizzato dalle sottoclassi, ogni sotto classe è poi istanziata con il tipo di messaggio che sarà poi utilizzato dal metodo di default `getFormattedErrorMsg`

2020-11-17 16:08 UTC, gabro commented on src/main/scala/error/Error.scala
> +sealed abstract case class Error(errorMessage: String) {
ok, chiaro. Le mie considerazioni:

> sealed - per forzare la definizioni dei sottotipi nello stesso file

ci sta come ragionamento, ma in generale non è consigliato estendere le `case class`, anzi normalmente si consiglia di marcarle come `final`. Qualche info in più qui https://nrinaudo.github.io/scala-best-practices/tricky_behaviours/final_case_classes.html

> case - per poter utilizzare il pattern matching su questo tipo di oggetti

ci sta, ma `case class` ha anche connotazioni più importanti, cioè il trattare quella classe come un contenitore puro ed immutabile di dati

> abstract class - lo scopo era avere una classe con un metodo di default per mostrare l'errore, in modo che potesse essere utilizzato dalle sottoclassi, ogni sotto classe è poi istanziata con il tipo di messaggio che sarà poi utilizzato dal metodo di default getFormattedErrorMsg 

Chiara la volontà, non è probabilmente il modo più comune di farlo in Scala. Innanzitutto estendere le case class non è consigliato (vedi sopra) e in secondo luogo in Scala si privilegia il polimorfismo ad-hoc rispetto al polimorfismo per subtyping. Qui un articolo che spiega bene le differenze tra i vari tipi di polimorfismo https://medium.com/@toidiu/polymorphism-in-scala-8bed74c9ff7c

In generale l'idea è quella di separare i data type dal loro 'behavior', in modo da potere comporre i due in maniera più flessibile

Per esempio

```scala
// la "famiglia" di data type `Error` rappresenta solo i dati, ma non ha nessun 'behavior' associato
sealed trait Error {
  def message: String
}
object Error {
  case class ErrorA(message: String) extends Error
  case class ErrorB(message: String) extends Error 
}
```

A questo punto non abbiamo detto nulla sulle operazioni possibili per `Error`.

Potremmo per esempio voler stampare quell'errore a schermo o serializzarlo in json, ma non lo stiamo definendo in maniera "fissa" nella definizione di `Error`.

Per esempio, supponiamo ora che tu voglia definire il behavior di "formattare l'errore per stamparlo a schermo". Generalmente in Scala si fa con un `trait`

```scala
trait Debuggable[A] {
  def debugMessage(a: A): String
}
```

Ora abbiamo:
- il data type `Error`, con tutti i suoi "figli"
- il behavior `Debuggable`


Proviamo ora a scrivere un metodo che ci consenta di stampare un errore di debug per *tutti* i tipi che implementino il comportamento `Debuggable`:

```scala
def printDebugMessage[A](a: A)(implicit d: Debuggable[A]): Unit =
  println(d.debugMessage(a))
```

Cose da notare:
- il metodo è generico in `A`. Si può anche leggere come "per ogni A", quindi vale per tutti i tipi esistenti
- ma noi vogliamo limitarlo solo a quelli per cui esiste `Debuggable` -> ed è qui che usiamo `implicit d: Debuggable[A]`. Stiamo chiedendo a Scala di verificare che il tipo `A` (che viene risolto ad un tipo specifico in fase di utilizzo del metodo) abbia implementato `Debuggable`. Se l'ha implementata, stiamo "bindando" l'implementazione a `d`.
- a questo punto possiamo usare `d` che conterrà il metodo `debugMessage`


A questo punto ci rimane solo da implementare `Debuggable` per `Error`:

```scala
implicit val errorDebuggable = new Debuggable[Error] {
  def debugMessage(e: Error): String = s"--> [${e.message}] !!!"
}
```

Proviamo ad usarlo:

```scala
printDebugMessage(Error.ErrorA("foo")) // ok
printDebugMessage("foobar") // errore, perché non esiste un `Debuggable` per `String`
```

La cosa bella di questo approccio è che il data type e il "behavior" (che in gergo si chiama type class) sono completamente disaccoppiate. Per esempio è possibile prendere un data type esistente non sotto il nostro controllo (ad esempio `String`) e associargli un behavior a piacere.

Esempio:

```scala
implicit val stringDebuggable = new Debuggable[Error] {
  def debugMessage(s: String): String = s"--> [$s] !!!"
}
```

e adesso per magia questo funzionerà:

```scala
printDebugMessage("foobar") // 
```


Una nota finale su `implicit`: tutto questo funziona perfettamente anche senza `implicit`, semplicemente `implicit` ci aiuta a non passare a mano in giro cose. Esempio completo senza `implicit`:

```scala
val errorDebuggable = new Debuggable[Error] {
  def debugMessage(e: Error): String = s"--> [${e.message}] !!!"
}

def printDebugMessage[A](a: A)(d: Debuggable[A]): Unit =
  println(d.debugMessage(a))

printDebugMessage(Error.ErrorA("foo"))(errorDebuggable) // ok
printDebugMessage("foo")(/* boh, cosa gli passo qui? */) // error
```

Spero sia utile :)

2020-11-18 08:32 UTC, gabro approved these changes, later dismissed
👍 ho lasciato qualche suggerimento super minor, ma overall molto bene! :-)

2020-11-18 08:32 UTC, gabro commented on src/main/scala/error/Error.scala
> +final object InvalidInput extends Error {
non c'è bisogno di rendere `final` gli `object` perché non si possono comunque estendere

2020-11-18 08:32 UTC, gabro commented on src/main/scala/game/Game.scala
> +        println(s"Math result  : ${matchResult}\n\n")
```suggestion
        println(s"Match result  : ${matchResult}\n\n")
```

2020-11-18 08:32 UTC, gabro commented on src/main/scala/game/Game.scala
> +        println(s"[User] ${userMove.toString()} <-> ${cpuMove.toString()} [CPU]")
ci sta farlo esplicito, ma sappi che `.toString` viene invocato in automatico quando fai string interpolation

2020-11-18 08:32 UTC, gabro commented on src/main/scala/game/Game.scala
> +        Exit
bellino l'uso di `Either.cond` :-)

2020-11-18 08:32 UTC, gabro commented on src/main/scala/game/Game.scala
> +      playAgain => play()
```suggestion
      _ => play()
```

(visto che non lo usi)

2020-11-18 08:46 UTC, gabro approved these changes

2020-11-18 08:47 UTC, merged