7 step 3 move as
buildo/caprio-be-training pull request #8
Opened 2020-11-18 14:57 UTC by Viktor-K

**TEST PLAN**
User input is validated with length criteria and available chars.
ADT data is used for matching players moves

2020-11-18 15:19 UTC, gabro requested changes
Bello l'utilizzo di validation da cats! Ho lasciato qualche commento.

Come mai non hai usato hophop per questa PR come ci eravamo detti?

2020-11-18 15:19 UTC, gabro commented on project/plugins.sbt
> +addSbtPlugin("org.lyranthe.sbt" % "partial-unification" % "1.1.2")
no need, stai usando 2.13.3 che ha partial unification abilitata di default

2020-11-18 15:19 UTC, gabro commented on src/main/scala/game/Game.scala
> +    case _ => Left(InputParsingError) // maybe unreachable
perché unreachable? Se l'utente passa "4" cosa succede?

2020-11-18 15:19 UTC, gabro commented on src/main/scala/validation/InputValidation.scala
> +      .mapN((_, _) => UserInputData(input))
```suggestion
      .mapN(_ => UserInputData(input))
```

volendo

2020-11-18 15:19 UTC, gabro commented on src/main/scala/game/Game.scala
> +  def handleErrorsList(errors: NonEmptyChain[Error]): Either[Command.Exit.type, Command.PlayAgain.type] = {
nitpick, ma non è una list :P 

`handleErrors` andrebbe benissimo a mio parere

2020-11-18 15:19 UTC, gabro commented on src/main/scala/game/Game.scala
> +        exit => Left(Exit)
```suggestion
        _ => Left(Exit)
```

2020-11-18 15:31 UTC, Viktor-K commented
> Bello l'utilizzo di validation da cats! Ho lasciato qualche commento.
> 
> Come mai non hai usato hophop per questa PR come ci eravamo detti?

La creazione del feature branch è stata eseguita senza errori, mentre al momento della creazione della PR ho registrato alcuni errori, per non tardare troppo la fase di review ho terminato la creazione della PR manualmente per poi passare a capire il tipo di errore.
Di seguito l'errore
<img width="1101" alt="Screenshot 2020-11-18 at 16 25 21" src="https://user-images.githubusercontent.com/5895397/99550352-f2420180-29ba-11eb-9db8-263300bc7a97.png">

2020-11-19 14:29 UTC, gabro approved these changes

2020-11-19 14:50 UTC, merged